flaskqa/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

from .extensions import db 

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50))
    password = db.Column(db.String(100))
    expert = db.Column(db.Boolean)
    admin = db.Column(db.Boolean)

    questions_asked = db.relationship(
        'Question', 
        foreign_keys='Question.asked_by_id', 
        backref='asker', 
        lazy=True
    )

    answers_requested = db.relationship(
        'Question',
        foreign_keys='Question.expert_id',
        backref='expert',
        lazy=True
    )

    @property
    def unhashed_password(self):
        raise AttributeError('Cannot view unhashed password!')

    @unhashed_password.setter
    def unhashed_password(self, unhashed_password):
        self.password = generate_password_hash(unhashed_password)

class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.Integer)
    answer = db.Column(db.Integer)
    asked_by_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    expert_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    nist_id = db.Column(db.String)
    nist_function = db.Column(db.String)
    nist_subcategory = db.Column(db.String)
    justification = db.Column(db.Text)

flaskqa/__init__.py
from flask import Flask
from .commands import create_tables
from .extensions import db, login_manager
from .models import User
from .routes.auth import auth
from .routes.main import main

def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)
    app.secret_key = b'\x10\x06@.\xcb\xac\xdb\xa7\xe8\x8d\xedi\x80O\ta.\xcc\x8a\x03&\x10C&'

    db.init_app(app)

    login_manager.init_app(app)

    login_manager.login_view = 'auth.login'

    @login_manager.user_loader
    def user_loader(user_id):
        return User.query.get(user_id)

    app.register_blueprint(main)
    app.register_blueprint(auth)

    app.cli.add_command(create_tables)

    return app

flaskqa/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash
from flaskqa.extensions import db
from flaskqa.models import User

auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        name = request.form['name']
        unhashed_password = request.form['password']

        user = User(
            name=name, 
            unhashed_password=unhashed_password,
            admin=False,  
            expert=True
        )

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('auth.login'))

    return render_template('register.html')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        name = request.form['name']
        password = request.form['password']

        user = User.query.filter_by(name=name).first()

        error_message = ''

        if not user or not check_password_hash(user.password, password):
            error_message = 'Could not login. Please check and try again.'

        if not error_message:
            login_user(user)
            return redirect(url_for('main.chart'))

    return render_template('login.html')

@auth.route('/logout')
def logout():   
    logout_user()
    return redirect(url_for('auth.login'))

flaskqa/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from flaskqa.extensions import db
from flaskqa.models  import Question, User
from sqlalchemy import func
from sqlalchemy.sql import label

main = Blueprint('main', __name__)


@main.route('/')
def index():
    if current_user.is_authenticated:
        questions = Question.query.filter(Question.answer != None).all()

        context = {
            'questions' : questions
        }
        return render_template('answers.html', **context)
    else:
        return render_template('landing.html')

@main.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    if request.method == 'POST':
        question = request.form['question']
        expert = request.form['expert']

        question = Question(
            question=question, 
            expert_id=expert, 
            asked_by_id=current_user.id
        )

        db.session.add(question)
        db.session.commit()

        return redirect(url_for('main.index'))

    experts = User.query.filter_by(expert=True).all()
    context = {
        'experts' : experts
    }
    return render_template('ask.html', **context)

@main.route('/answer/<int:question_id>', methods=['GET', 'POST'])
@login_required
def answer(question_id):
    if not current_user.expert:
        return redirect(url_for('main.index'))

    question = Question.query.get_or_404(question_id)

    if request.method == 'POST':
        question.answer = request.form['answer']
        question.justification = request.form['justification']

        db.session.commit()

        return redirect(url_for('main.unanswered'))

    context = {
        'question' : question
    }

    return render_template('answer.html', **context)

@main.route('/question/<int:question_id>', methods=['GET', 'POST'])
@login_required
def question(question_id):
    if not current_user.expert:
        return redirect(url_for('main.index'))

    question = Question.query.get_or_404(question_id)

    if request.method == 'POST':
        question.answer = request.form['answer']

        db.session.commit()
        
        return redirect(url_for('main.unanswered'))
    context = {
        'question' : question
    }

    return render_template('question.html', **context)

@main.route('/unanswered')
@login_required
def unanswered():
    if not current_user.expert:
        return redirect(url_for('main.index'))

    unanswered_questions = Question.query\
    .filter_by(expert_id=current_user.id)\
    .filter(Question.answer == None)\
    .all()

    context = {
        'unanswered_questions' : unanswered_questions
    }

    return render_template('unanswered.html', **context)

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/users')
@login_required
def users():
    if not current_user.admin:
        return redirect(url_for('main.index'))

    users = User.query.filter_by(admin=False).all()

    context = {
        'users' : users
    }

    return render_template('users.html', **context)

@main.route('/chart')
@login_required
def chart():

    # legend = 'Profile'
    labels = ["Identify", "Detect", "Protect", "Respond", "Recover"]
    
    Identify = Question.query.with_entities(func.avg(Question.answer)).filter_by(nist_function="ID").scalar() 
    Protect = Question.query.with_entities(func.avg(Question.answer)).filter_by(nist_function="PR").scalar() 
    Detect = Question.query.with_entities(func.avg(Question.answer)).filter_by(nist_function="DE").scalar() 
    Respond = Question.query.with_entities(func.avg(Question.answer)).filter_by(nist_function="RS").scalar() 
    Recover = Question.query.with_entities(func.avg(Question.answer)).filter_by(nist_function="RC").scalar() 

    # for n in nist_function:
    #     question.query.with_entities(func.avg(Question.answer)).filter_by(nist_function="label").scalar()

    values = [Identify,Protect,Detect,Respond,Recover]

    context = {
        'values' : values
    }

    return render_template('chart.html', **context)


@main.route('/promote/<int:user_id>')
@login_required
def promote(user_id):
    if not current_user.admin:
        return redirect(url_for('main.index'))

    user = User.query.get_or_404(user_id)

    user.expert = True
    db.session.commit()     

    return redirect(url_for('main.users'))

flaskqa/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}

{% block content %}
<main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
          <div class="container">
            <h1 class="display-3">Hello, world!</h1>
            <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
            <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
          </div>
        </div>
      
        <div class="container bg-dark">
          <!-- Example row of columns -->
          <div class="row text-white">
            <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
            </div>
            <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
              <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
            </div>
            <div class="col-md-4">
              <h2>Heading</h2>
              <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
              <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
            </div>
          </div>
      
          <hr>
      
        </div> <!-- /container -->
      
      </main>
{% endblock %}

flaskqa/templates/answer.html
{% extends 'base.html' %}
{% block title %}Answer Question{% endblock %}

{% block content %}
  <div class="jumbotron bg-secondary text-light">
      <div class="page-header">
        <h1>{{ question.question }}</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('main.answer', question_id=question.id) }}">
                <fieldset>
                  <div class="form-group">
                    <label for="select" class="col-lg-2 control-label">Tier</label>
                      <div class="col-lg-10">
                        <select class="form-control" name="answer" id="select">
                          <option value="1">1</option>
                          <option value="2">2</option>
                          <option value="3">3</option>
                          <option value="4">4</option>
                        </select>
                      </div>
                    </div>
                  <div class="form-group">
                    <label for="textArea" class="col-lg-2 control-label">Justification</label>
                      <div class="col-lg-10">
                        <textarea type="text" class="form-control" name="justification" rows="2" id="textArea"></textarea>
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-primary">Submit</button>
                      </div>
                    </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

flaskqa/templates/answers.html
{% extends 'base.html' %}
{% block title %}Oversight{% endblock %}

{% block content %}
      <div class="page-header text-white">
        <h1>Answered Questions</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
            {% for question in questions %}
              <a href="{{ url_for('main.question', question_id=question.id) }}" class="list-group-item p-3 mb-2 bg-secondary text-white">
                <h4 class="list-group-item-heading">{{ question.question }}</h4>
                <p class="list-group-item-text">Asked by: {{ question.asker.name }}</p>
                <p class="list-group-item-text">Answered by: {{ question.expert.name }}</p>
                <p class="list-group-item-text">Function: {{ question.nist_function }}</p>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flaskqa/templates/ask.html
{% extends 'base.html' %}
{% block title %}Ask a Question{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Ask A Question</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="well bs-component">
            <form class="form-horizontal" method="POST" action="{{ url_for('main.ask') }}">
              <fieldset>
                <div class="form-group">
                  <label for="textArea" class="col-lg-2 control-label">Question</label>
                    <div class="col-lg-10">
                      <textarea class="form-control" name="question" rows="3" id="textArea"></textarea>
                      <span class="help-block">Ask away!</span>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="select" class="col-lg-2 control-label">Expert</label>
                    <div class="col-lg-10">
                      <select class="form-control" name="expert" id="select">
                        {% for expert in experts %}
                        <option value="{{ expert.id }}">{{ expert.name }}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

flaskqa/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
    <link rel="shortcut icon" sizes="32x32" href="{{ url_for('static', filename='favicon.ico') }}">
  </head>

  <body class="bg-dark">
  
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary mb-4">
      <div class="container">
        <div class="navbar-header">
        <a class="navbar-brand" href="#">Oversight</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
              <li class="nav-link"><a class="text-white" href="{{ url_for('main.chart') }}">Profile </a></li>
            {% endif %}
            {% if current_user.is_authenticated and current_user.expert %}
              <li class="nav-link"><a class="text-white" href="{{ url_for('main.unanswered') }}">Questions</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
              <li class="nav-link"><a class="text-white" href="{{ url_for('main.index') }}">Answers</a></li>
            {% endif %}
            {% if not current_user.is_authenticated %}
              <li class="nav-link"><a class="text-white" href="{{ url_for('main.about') }}">About</a></li>
              <li class="nav-link"><a class="text-white" href="{{ url_for('auth.login') }}">Login</a></li>
              <li class="nav-link"><a class="text-white" href="{{ url_for('auth.register') }}">Register</a></li>
            {% endif %}
            <!-- {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('main.ask') }}">Ask Question</a></li>
            {% endif %} -->
            {% if current_user.is_authenticated and current_user.admin %}
              <li class="nav-link"><a class="text-white" href="{{ url_for('main.users') }}">Users</a></li>
            {% endif %}
            {% if current_user.is_authenticated %}
              <li class="nav-link"><a class="text-white" href="{{ url_for('auth.logout') }}">Logout</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    

    <div class="container theme-showcase" role="main">

      {% block content %}{% endblock %}

    </div> <!-- /container -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  </body>
</html>

flaskqa/templates/chart.html
{% extends 'base.html' %}
{% block title %}Chart{% endblock %}

{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
<canvas id="myChart"></canvas>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'radar',
    data: {
        labels : ["Identify", "Detect", "Protect", "Respond", "Recover"],
        datasets: [{
            label: 'Current',
            data: [{% for value in values -%}{{ value }},{% endfor -%}],
            backgroundColor: [
                'rgba(0, 176, 240, 0.4)',
                'rgba(, 176, 140, 0.2)',
                'rgba(255, 106, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            color: [
                'rgba(255, 25, 0, 1)'
            ],
            borderColor: [
                'rgba(255, 255, 255, 1)',
                'rgba(255, 255, 255, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ]
        }],
    },
    options: {
        scale: {
            pointLabels: {
                fontSize: 14
            },
            gridLines: {
                color: 'rgba(201, 201, 201, 0.1)',
                lineWidth: 2.2
            },
            ticks: {
                beginAtZero: true,
                max: 4,
                min: 0,
                stepSize: 1
            }
        },
    legend: {
        defaultfontSize: "60",
        labels: {
            // This more specific font property overrides the global property
            defaultFontColor: 'white',
            }
        }
    }
});
</script>
{% endblock %}

flaskqa/templates/home.html
{% extends 'base.html' %}
{% block title %}Oversight{% endblock %}

{% block content %}
      <div class="page-header">
        <h1>Answered Questions</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
            {% for question in questions %}
              <a href="{{ url_for('main.question', question_id=question.id) }}" class="list-group-item">
                <h4 class="list-group-item-heading">{{ question.question }}</h4>
                <p class="list-group-item-text">Asked by: {{ question.asker.name }}</p>
                <p class="list-group-item-text">Answered by: {{ question.expert.name }}</p>
                <p class="list-group-item-text">Function: {{ question.nist_function }}</p>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flaskqa/templates/landing.html
{% extends 'base.html' %}
{% block title %}Oversight{% endblock %}

{% block content %}
<main role="main">

    <div id="myCarousel" class="carousel slide img-fluid" data-ride="carousel" style="height:10%; margin:10px">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <!-- Wrapper for carousel items -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="static/landing_1.png" alt="First Slide">
            </div>
            <div class="carousel-item">
                <img src="static/landing_2.png" alt="Second Slide">
            </div>
            <div class="carousel-item">
                <img src="static/landing_3.png" alt="Third Slide">
            </div>
        </div>
        <!-- Carousel controls -->
        <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="container marketing text-white">

    <!-- Three columns of text below the carousel -->
    <div class="row">
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h2>Heading</h2>
        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h2>Heading</h2>
        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div><!-- /.col-lg-4 -->
      <div class="col-lg-4">
        <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"></rect><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div><!-- /.col-lg-4 -->
    </div><!-- /.row -->


    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It’ll blow your mind.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
          <img src="static/Screen-Mockup_01.png" class="img-fluid" alt="Responsive image">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Oh yeah, it’s that good. <span class="text-muted">See for yourself.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5 order-md-1">
          <img src="static/Screen-Mockup_02.png" class="img-fluid" alt="Responsive image">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
      </div>
      <div class="col-md-5">
          <img src="static/Screen-Mockup_03.png" class="img-fluid" alt="Responsive image">
      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>© 2017-2019 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
  </footer>
</main>
{% endblock %}

flaskqa/templates/question.html
{% extends 'base.html' %}
{% block title %}Question{% endblock %}

{% block content %}
<div class="jumbotron bg-secondary text-white">
        <h1>{{ question.question }}</h1>
        <h2>Tier: {{ question.answer }}</h2>
        <h2>Justification: {{ question.justification }}</h2>
        <p><a class="btn btn-primary btn-md">Asked By: {{ question.asker.name }}</a></p>
        <p><a class="btn btn-primary btn-md">Answered By: {{ question.expert.name }}</a></p>
        <p><a class="btn btn-primary btn-sm">NIST ID: {{ question.nist_id }}</a></p>
        <p><a class="btn btn-primary btn-sm">NIST Function: {{ question.nist_function }}</a></p>
      </div>
{% endblock %}

flaskqa/templates/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}

{% block content %}
<div class="jumbotron">
<div class="page-header">
        <h1>Register</h1>
      </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="well bs-component">
              <form class="form-horizontal" method="POST" action="{{ url_for('auth.register') }}">
                <fieldset>
                  <div class="form-group">
                    <label for="inputName" class="col-lg-2 control-label">Name</label>
                    <div class="col-lg-10">
                      <input type="text" class="form-control" name="name" id="inputName" placeholder="Name">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                    <div class="col-lg-10">
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                      <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                  </div>
                </fieldset>
              </form>
            </div>
          </div>
        </div>
{% endblock %}

flaskqa/templates/unanswered.html
{% extends 'base.html' %}
{% block title %}Unaswered Questions{% endblock %}

{% block content %}
<div class="page-header text-white">
        <h1>Questions For You</h1>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
              {% for question in unanswered_questions %}
                <a href="{{ url_for('main.answer', question_id=question.id) }}" class="list-group-item p-3 mb-2 bg-secondary text-white">
                  <h4 class="list-group-item-heading">{{ question.question }}</h4>
                  <p class="list-group-item-text">Asked by: {{ question.asker.name }}</p>
                </a>
              {% endfor %}
            <!-- {% if unanswered_questions == 0 %}
              <h4>You have no assigned questions at this stage.</h4>
            {% endif %} -->
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
{% endblock %}

flaskqa/templates/users.html
{% extends 'base.html' %}
{% block title %}Users{% endblock %}

{% block content %}
<div class="jumbotron">
<div class="page-header">
        <h1>Users</h1>
        <h6>Click to promote to expert</h6>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="list-group">
            {% for user in users %}
              <a href="{{ url_for('main.promote', user_id=user.id) }}" class="list-group-item {% if user.expert %}active{% endif %}">
                <h4 class="list-group-item-heading">{{ user.name }}</h4>
              </a>
            {% endfor %}
          </div>
        </div><!-- /.col-lg-12 -->
      </div>
    </div>
{% endblock %}